/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_6;

public class App {
   

    public static void main(String[] args) {
        int i = 20;
        do{
            System.out.println(i);
            i--;
        }
        while(i > 0);
    }
}
