/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejerSalario;
import java.util.Scanner;
public class App {
    

    public static void main(String[] args) {
        int horas;
        int mHoras;
        int euros = 0;
        System.out.println("Introduce el número de horas trabajadas: ");
        Scanner teclado = new Scanner(System.in);
        horas = teclado.nextInt();
       
       if(horas <= 40){
           euros = horas * 15;
       }
       else if (horas >= 41){
           euros = 40 * 15;
           mHoras = horas - 40;
           euros = euros + (mHoras * 20);
       }
       System.out.println("Salario semanal: " + euros);
    }
}
