/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_4;

public class App {

    public static void main(String[] args) {
        for(int i = 20; i > 0; i--){
            System.out.println(i);
        }
    }
}
