/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        System.out.println("Introduce un numero y se mostrarán a pantalla los primeros 10 múltiplos: ");
        int num = myScanner.nextInt();

        for (int i = 1; i <= 10; i++) {
            System.out.println("Múltiplo " + i + ": " + num * i);
        }
    }
}
