/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ordenarNum;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int mayor = 0;
        int menor = 0;
        int medio = 0;
        int n1, n2, n3;
        Scanner teclado = new Scanner(System.in);
        System.out.println("Introduce el primer numero: ");
        n1 = teclado.nextInt();
        System.out.println("Introduce el segundo numero: ");
        n2 = teclado.nextInt();
        System.out.println("Introduce el tercer numero: ");
        n3 = teclado.nextInt();

        if (n1 > n2 && n1 > n3) {
            mayor = n1;
        } else if (n2 > n1 && n2 > n3) {
            mayor = n2;
        } else if (n3 > n2 && n3 > n1) {
            mayor = n3;
        }

        if (n1 < n2 && n1 < n3) {
            menor = n1;
        } else if (n2 < n1 && n2 < n3) {
            menor = n2;
        } else if (n3 < n2 && n3 < n1) {
            menor = n3;
        }

        if (n1 > n2 && n1 < n3) {
            medio = n1;
        } else if (n2 > n1 && n2 < n3) {
            medio = n2;
        } else if (n3 > n2 && n3 < n1) {
            medio = n3;
        }

        if (n1 == n2 && n1 == n3 || n1 == n2 || n1 == n3 || n2 == n3) {
            System.out.println("Hay dos o tres números iguales");
        } else {
            System.out.println("Mayor: " + mayor);
            System.out.println("Medio: " + medio);
            System.out.println("Menor: " + menor);
        }
    }
}
