/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_3;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        int cont = 1;
        Scanner myScanner = new Scanner(System.in);
        System.out.println("Introduce un número y se mostrarán en pantalla los 10 primeros múltiplos: ");
        int num = myScanner.nextInt();

        do {
            System.out.println(num * cont);
            cont++;
        } while (cont <= 10);
    }
}
