/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_5;

public class App {
    

    public static void main(String[] args) {
        int i = 20;
        while(i > 0){
            System.out.println(i);
            i--;
        }
    }
}
