/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.EjerVariables_2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        System.out.println("Dame un número x: ");
        int x = myScanner.nextInt();
        System.out.println("Dame un número y: ");
        int y = myScanner.nextInt();
        int suma = x + y;
        int resta = x - y;
        int mult = x * y;
        int div = x / y;

        System.out.println("x = " + x);
        System.out.println("y = " + y);
        System.out.println("Suma = " + suma);
        System.out.println("Resta = " + resta);
        System.out.println("Multiplicación = " + mult);
        System.out.println("División = " + div);

    }
}
