/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.EjerVariables_3;

public class App {
   

    public static void main(String[] args) {
       String nombre = "Rubén";
       System.out.println("Tu nombre es " + nombre);
    }
}
