/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.EjerVariables_4;

public class App {
   
    public static void main(String[] args) {
        String nombre = "Rubén", dir = "Pérez de Ayala";
        int num = 619651329;
        System.out.println("Tu nombre es: " + nombre);
        System.out.println("Tu direccion es: " + dir);
        System.out.println("Tu número de teléfono es: " + num);
    }
}
