/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        int cont = 1;
        Scanner myScanner = new Scanner(System.in);
        System.out.println("Introduce un numero y se mostrarán a pantalla los 10 primeros múltiplos: ");
        int num = myScanner.nextInt();
        while (cont <= 10) {
            System.out.println(num * cont);
            cont++;
        }
    }
}
