/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejerNotas;
import java.util.Scanner;
public class App {
   

    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        double n1, n2, n3;
        double media = 0.0;
        System.out.println("Introduce la nota 1: ");
        n1 = teclado.nextDouble();
        System.out.println("Introduce la nota 2: ");
        n2 = teclado.nextDouble();
        System.out.println("Introduce la nota 3: ");
        n3 = teclado.nextDouble();
        
        media = (n1 + n2 + n3) / 3;
        System.out.println("La nota media es: " + media);
        
        if(media >= 8.5){
            System.out.println("Sobresaliente");
        }
        else if(media >= 7 && media < 8.5){
            System.out.println("Notable");
        }
        else if(media >= 6 && media < 7){
            System.out.println("Bien");
        }
        else if(media >= 5 && media < 6){
            System.out.println("Suficiente");
        }
        else if(media < 5){
            System.out.println("Insuficiente");
        }
    }
}
