/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.factura;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
        System.out.println("Este programa calculará una factura a partir de la base imponible, teniendo en cuenta el IVA y el IRPF.");
        Scanner teclado = new Scanner(System.in);
        
        System.out.println("Introduce la base imponible: ");
        int base = teclado.nextInt();
        System.out.println("Introduce el porcentaje de IVA: ");
        int pIva = teclado.nextInt();
        System.out.println("Introduce el porcentaje de IRPF: ");
        int pIrpf = teclado.nextInt();
        
        int iva = (pIva * base) / 100;
        int irpf = (pIrpf * base) / 100;
        int factura = base + iva - irpf;
        int factSinIva = base - irpf;
        
        System.out.println("El total de la factura con el IVA y el IRPF aplicados será de " + factura + " euros");
        System.out.println("La factura sin aplicar el IVA será de " + factSinIva + " euros");

    }
}
