/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.Bucles_7;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        int menu;
        String pass = "0000", passInput = "";
        Scanner myScanner = new Scanner(System.in);
        do {
            System.out.println("1. Asignar nueva combinación\n2. Abrir caja fuerte\n0. Salir");
            menu = myScanner.nextInt();

            switch (menu) {
                case 1:
                    System.out.println("Introduzca la combinación actual: ");
                    myScanner.nextLine();
                    passInput = myScanner.nextLine();
                    if (passInput.equals(pass)) {
                        System.out.println("Bien, introduzca la nueva combinación: ");
                        pass = myScanner.nextLine();
                        if (pass.length() == 4) {
                            System.out.println("Nueva combinación almacenada\n");
                        } else if (pass.length() != 4) {
                            do {
                                System.out.println("Error, la combinación tiene que ser de 4 dígitos, vuelva a introducirla: ");
                                pass = myScanner.nextLine();
                                if (pass.length() == 4) {
                                    System.out.println("Nueva combinación almacenada\n");
                                }
                            } while (pass.length() != 4);

                        }
                    } else {
                        System.out.println("Combinación errónea");
                    }
                    break;
                case 2:
                    System.out.println("Introduce la combinación correcta para abrir la caja fuerte");
                    myScanner.nextLine();
                    passInput = myScanner.nextLine();
                    if (passInput.equals(pass)) {
                        System.out.println("Caja fuerte abierta\n");
                    } else {
                        System.out.println("Combinación errónea\n");
                    }
                    break;

            }

        } while (menu != 0);
    }
}
